### PR TITLE
feat(api): add delete api access endpoint

### PR DESCRIPTION
**Pull request by tleon**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Add a delete endpoint for api access.
| Type?             | new feature
| BC breaks?        |  no
| Deprecations?     | no
| Sponsor company   | PrestaShop SA

### CODE REVIEW

**Review by boherm — APPROVED** [review]
LGTM, thanks @tleon, specially for the dot in description 😇

**Review by mflasquin — APPROVED** [review]

**Review by nicosomb — APPROVED** [review]

**Comment by boherm** [comment]
I think that we are not officially committers in this repository, no? 😅

**Comment by matks** [comment]
There was no github configuration for teams on this repository. It has been fixed.

**Comment by nicosomb** [comment]
@tleon is there a "how to test"?

**Comment by tleon** [comment]
not really yet. @jolelievre asked me to do this because QA team need this endpoint to write some tests

**Pull request merged**
